name: Mike Filsaime
favicon: null
layout_spectrum: 0.08441850962117314
typography_spectrum: 0.6044883274007589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.630447459872812
  lightness: 0.33365315361879766
  saturation: 0.9381517502479255
  rhythmicContrast: 0.7411333657801151
purpose: []
