name: Mike Filsaime
favicon: null
layout_spectrum: 0.08441850962117314
typography_spectrum: 0.63811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e6e6e6'
    - '#2b719d'
    - '#c41229'
    - '#c56995'
  brandStrength: 0.630447459872812
  lightness: 0.33365315361879766
  saturation: 0.9381517502479255
  rhythmicContrast: 0.7411333657801151
purpose: []
